### ISSUE TITLE
Cmakelist bug

### ISSUE THREAD

**Issue by zzusunquan** [faultaddr/3DViewer#1]
![image](https://user-images.githubusercontent.com/48703273/174998924-5ed79887-ea07-4a08-be07-5e9f898653ab.png)
log目录下还没有CMakeLissts.txt

**Comment by zzusunquan** [comment]
![image](https://user-images.githubusercontent.com/48703273/174999245-323c410c-6733-467a-9052-5f3d8a8d87eb.png)

**Comment by zzusunquan** [comment]
注释掉 add_executable 之后会出现以下问题
![image](https://user-images.githubusercontent.com/48703273/174999786-24569fd8-1079-4be2-9458-add32593ed3b.png)

**Comment by zzusunquan** [comment]
应该是我没装 glog

**Comment by faultaddr** [comment]
well, the reason why u have these issues would like to be u haven't clone the submodule repository.
### How to Solve the Problem
- install the glog, include the header file && link the glog library
- git clone the glog, move it into src
