### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by gleke** [faultaddr/3DViewer#7]
使用 cmake 配置和生成。

cmake -H. -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=on

使用 make 构建。

cd build
make

gleke@gleke-QTJ5:~/3DViewer$ cmake -H. -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=on
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_C_COMPILER:

    /usr/bin/clang

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_CXX_COMPILER:

    /usr/bin/clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/gleke/3DViewer/build/CMakeFiles/CMakeOutput.log".
See also "/home/gleke/3DViewer/build/CMakeFiles/CMakeError.log".
gleke@gleke-QTJ5:~/3DViewer$ ls
3DViewer.INFO  build  CMakeLists.txt  LICENSE  README.md  src
gleke@gleke-QTJ5:~/3DViewer$ cd buils
bash: cd: buils: 没有那个文件或目录
gleke@gleke-QTJ5:~/3DViewer$ cd build
gleke@gleke-QTJ5:~/3DViewer/build$ make
make: *** 没有指明目标并且找不到 makefile。 停止。
gleke@gleke-QTJ5:~/3DViewer/build$

**Comment by gleke** [comment]
系统环境：ubuntu180.4  qt5.15.4

**Comment by faultaddr** [comment]
> 系统环境：ubuntu180.4 qt5.15.4

sudo apt-get install llvm
sudo apt-get install clang

Please use English for better communication
